### PR TITLE
html and css linter config

### PR DESCRIPTION
**Pull request by Kidd254**
In this branch I configured linter, made some corrections, and added a descriptive README

### CODE REVIEW

**Review by isaacpitwa — CHANGES_REQUESTED** [review]
Hi @Kidd254  🙂 ,

You have done a tremendous job setting up your project. I really like it :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

Alt Text


## Highlights 
- All linters are passing  ✅
- Correct use of GitHub flow ✅
- Well documented Repository ✅
-  Clean and readable code base ✅

## Required changes ♻️ 

- [ ] projects missing The 2 sections you need to build for this project  thas is 
      - **the toolbar** 
      - and **the headline section** (right after the header)
       as stated in the[ project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md)

- Check the comments under the review.

 Kindly make sure to display all the contents according to the correct width, height, size as per shown in the video attached.
Check the comments under the review.

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Check the comments under the review.





Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @isaacpitwa.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by alexpuente0 — CHANGES_REQUESTED** [review]
Hi @Kidd254, 

You've done a great job so far!

In this case, however, there are still some issues that you need to work on to finish this project and advance to the next one, but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alexpuente0** [comment]
- [ ] You seem to be missing a bit of spacing between elements. Please make sure you apply the proper margin/padding provided by the template on each element to separate them from the edges and distance them from each other.

Your design:
image

Template:
image

**Comment by alexpuente0** [comment]
- [ ] [OPTIONAL] Please try to reinstall the linter files, as they are a requirement for the project and they help you keep your code in order.

**Comment by Kidd254** [comment]
hello, alexpuente0 ..the errors are only appearing on the vs code studio terminal after i run npx stylelint "**/*.{css,scss}"....how do i make them appear on my repository? kindly get back to me as soon as you get this.

**Comment by Kidd254** [comment]
> hello, @alexpuente0 ..the errors are only appearing on the vs code studio terminal after i run npx stylelint "**/*.{css,scss}"....how do i make them appear on my repository? kindly get back to me as soon as you get this.

**Comment by alexpuente0** [comment]
> > hello, @alexpuente0 ..the errors are only appearing on the vs code studio terminal after i run npx stylelint "**/*.{css,scss}"....how do i make them appear on my repository? kindly get back to me as soon as you get this.
> 
> 

Sorry for the late responde. In order to load the linters into your repository you need to push a linters.yml file inside the '.github/workflows' path that you should create on your project's root.

You can see how to redo It with Full detail on [this page](https://github.com/microverseinc/linters-config/blob/master/html-css/README.md).

**Comment by Kidd254** [comment]
thanks for the review and the positive responses

**Pull request merged**
